import Head from 'next/head'
import { useContext } from 'react'
import Button from '../components/atm/Button'
import LoginModal from '../components/org/modals/LoginModal'
import SignupModal from '../components/org/modals/SignupModal'
import { GlobalContext } from '../hooks/viewmodels/useGlobalViewModel'

export default function Home() {
  const globalViewModel = useContext(GlobalContext)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        display: 'flex',
        gap: '8px'
        }}>
        <Button onClick={() => globalViewModel.openLoginModal()}>ログイン</Button>
        <Button onClick={() => globalViewModel.openSignupModal()}>新規登録</Button>
      </div>
      <LoginModal isOpen={globalViewModel.isLoginOpen} onClose={() => globalViewModel.closeLoginModal()} />
      <SignupModal isOpen={globalViewModel.isSignupOpen} onClose={() => globalViewModel.closeSignupModel()} />
    </>
  )
}
